version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sCEMzoGpWLWjaQGpKLsSrOkKFJbhyQul
      - POSTGRES_DB=yb_bank_dev
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local